"$schema" = "https://starship.rs/config-schema.json"

format = """
[](neon_amber)$os$username[](neon_amber) \
[](neon_blue)$directory[](neon_blue) \
[](neon_pink)$git_branch$git_status[](neon_pink) \
[](bg_light)$c$rust$golang$nodejs$php$java$kotlin$haskell$python[](bg_light) \
[](bg_dark)$docker_context$conda$aws[](bg_dark) \
[](bg_deep)$time[](bg_deep) \
$line_break$character"""
palette = "cyberpunk_neon"

[palettes.cyberpunk_neon]
bg_deep = "#0e0b16"
bg_dark = "#1b1630"
bg_light = "#241e3d"
neon_amber = "#ffb300"
neon_blue = "#4fc3ff"
neon_purple = "#b96cff"
neon_pink = "#ff4fd8"
text_fg = "#e6e2f2"

[os]
disabled = false
style = "bg:neon_amber fg:bg_deep"
format = "[$symbol]($style)"

[os.symbols]
Arch = " "
Debian = " "

[username]
show_always = true
style_user = "bg:neon_amber fg:bg_deep"
style_root = "bg:neon_amber fg:bg_deep"
format = "[$user]($style)"

[directory]
style = "fg:bg_deep bg:neon_blue"
format = "[$path]($style)"

[git_branch]
symbol = ""
style = "fg:bg_deep bg:neon_pink"
format = "[$symbol $branch]($style)"

[git_status]
style = "fg:bg_deep bg:neon_pink"
format = "[($all_status$ahead_behind )]($style)"

[nodejs]
symbol = ""
style = "fg:neon_blue bg:bg_light"
format = "[$symbol( $version)]($style)"

[python]
symbol = ""
style = "fg:neon_blue bg:bg_light"
format = "[$symbol( $version)]($style)"

[rust]
symbol = ""
style = "fg:neon_blue bg:bg_light"
format = "[$symbol( $version)]($style)"

[aws]
symbol = ""
style = "fg:neon_blue bg:bg_dark"
format = "[$symbol( $profile - $duration)]($style)"


[time]
disabled = false
time_format = "%R"
style = "fg:text_fg bg:bg_deep"
format = "[ $time]($style)"

[character]
success_symbol = "[](bold neon_blue)"
error_symbol = "[](bold neon_pink)"
# Vim mode symbols
vimcmd_symbol = "[](bold neon_purple)"
vimcmd_replace_one_symbol = "[](bold neon_pink)"
vimcmd_replace_symbol = "[](bold neon_pink)"
vimcmd_visual_symbol = "[](bold neon_blue)"
